package dev.jorgecastillo.lifecolors.common.view.extensions

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import dev.jorgecastillo.lifecolors.R

fun Context.copyToClipboard(text: String) {
  val clipboardService = getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
  val clip = ClipData.newPlainText("Color generated by Lifecolors app", text)
  clipboardService.primaryClip = clip
  Toast.makeText(this, R.string.feedback_copy_to_clipboard, Toast.LENGTH_SHORT).show()
}
